basic.showString("HELLO, ELIAS!")
TobbieII.shake_head(10)
basic.pause(500)
TobbieII.forward()
basic.pause(500)
TobbieII.backward()
basic.pause(500)
TobbieII.leftward()
basic.pause(500)
TobbieII.rightward()
basic.pause(500)
TobbieII.shake_head(10)
basic.pause(500)
TobbieII.stopturn()
basic.showIcon(IconNames.Heart)
basic.showString("HELLO, ELIAS!")
